# Generated by Django 5.0.6 on 2026-03-15 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('tournament', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_number', models.PositiveSmallIntegerField()),
                ('result', models.CharField(choices=[('PENDING', 'Pending'), ('WHITE_WIN', 'White Win'), ('BLACK_WIN', 'Black Win'), ('DRAW', 'Draw'), ('BYE', 'Bye'), ('FORFEIT', 'Forfeit')], default='PENDING', max_length=10)),
                ('is_bye', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('black', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pairings_as_black', to='participants.participant')),
                ('white', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pairings_as_white', to='participants.participant')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='rounds.round')),
            ],
            options={
                'ordering': ['board_number'],
                'unique_together': {('round', 'board_number')},
            },
        ),
    ]
